//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryDBFirst.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public string AddressTo { get; set; }
        public string DescriptionOfCargo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double Price { get; set; }
        public int CourierID_CourierID { get; set; }
        public int StatusID_OrderStatusID { get; set; }
    
        public virtual Couriers Couriers { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
    }
}
